'use strict';

// Strip AI co-authorship and "generated by AI" trailers from a commit message,
// while keeping legitimate human co-authors. The project rule forbids AI
// attribution in commits; human contributor co-authorship stays untouched.
//
// Detection keys off vendor/assistant names only. It deliberately does NOT key
// off github noreply emails, because human contributors use those too and their
// co-authorship must be preserved.

const AI_SIGNATURE = /(claude|anthropic|copilot|gemini|google[-\s]?labs|chatgpt|openai|\bgpt-?\d?\b|\bcursor\b|codeium|windsurf|\bdevin\b|tabnine|amazon\s+q|\bcody\b)/i;

// Full lines that are AI attribution regardless of trailer key. A leading run
// of non-word characters (a bullet or the robot emoji) is skipped with \W*, so
// this source needs no literal emoji.
const AI_GENERATED_LINE = /^\W*generated\s+(with|by)\b.*(claude|copilot|gemini|chatgpt|openai|\bai\b|code)\b/i;
const AI_ASSIST_TRAILER = /^\s*(co-authored-by|assisted-by|co-developed-with|generated-by|authored-by)\s*:/i;

function lineIsAiTrailer(line) {
  if (AI_GENERATED_LINE.test(line)) return true;
  if (AI_ASSIST_TRAILER.test(line) && AI_SIGNATURE.test(line)) return true;
  return false;
}

// Returns { message, removed } where removed is the list of stripped lines.
// Only AI attribution is removed; human co-authors and the rest of the message
// are preserved. Trailing blank lines left behind are collapsed.
function stripAiCoauthorship(message) {
  const text = String(message === null || message === undefined ? '' : message);
  const lines = text.split('\n');
  const removed = [];
  const kept = [];

  for (const line of lines) {
    if (lineIsAiTrailer(line)) {
      removed.push(line);
    } else {
      kept.push(line);
    }
  }

  if (removed.length === 0) {
    return { message: text, removed };
  }

  while (kept.length > 0 && kept[kept.length - 1].trim() === '') {
    kept.pop();
  }

  const rebuilt = kept.join('\n');
  const message2 = text.endsWith('\n') ? `${rebuilt}\n` : rebuilt;
  return { message: message2, removed };
}

module.exports = { stripAiCoauthorship, lineIsAiTrailer };
