'use strict';
// Property test for the ordering invariant (#1252): interleaved multi-writer
// schedules generated by a hand-rolled LCG (fixed seeds, fully reproducible)
// must always reach a live subscriber with per-sender ordering intact, no
// loss and no duplicates. The generator shuffles WHICH writer appends next;
// each writer's own sequence stays monotonic at the source, and the
// invariant is that it stays monotonic at the sink too.

const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { loadSqliteDriver } = require('./lib/deps');
const { openStore, insertEvent, maxEventId, readSince } = require('./lib/store');
const { createWalWatcher } = require('./lib/wal-watcher');

const ROUNDS = 20;
const WRITERS = 3;
const EVENTS_PER_WRITER = 30;
const BASE_SEED = 0xE6C0FFEE;

function lcg(seed) {
  let state = seed >>> 0;
  return () => {
    state = (Math.imul(1664525, state) + 1013904223) >>> 0;
    return state / 2 ** 32;
  };
}

function shuffle(items, rand) {
  const list = [...items];
  for (let i = list.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1));
    [list[i], list[j]] = [list[j], list[i]];
  }
  return list;
}

async function drainUntil(db, watcher, fromId, expected, deadlineMs) {
  const deadline = Date.now() + deadlineMs;
  const received = [];
  let cursor = fromId;
  while (received.length < expected && Date.now() < deadline) {
    const events = await readSince(db, cursor);
    if (events.length > 0) {
      cursor = Number(events[events.length - 1].id);
      received.push(...events);
      continue;
    }
    await watcher.waitForChange(Math.min(300, Math.max(1, deadline - Date.now())));
  }
  return received;
}

async function round(driver, seed) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'egc-mesh-prop-'));
  const dbPath = path.join(dir, 'state.db');
  const db = await openStore(driver, dbPath);
  const watcher = createWalWatcher(dbPath);
  try {
    const rand = lcg(seed);
    const tokens = [];
    for (let w = 0; w < WRITERS; w++) {
      for (let i = 0; i < EVENTS_PER_WRITER; i++) tokens.push(w);
    }
    const schedule = shuffle(tokens, rand);

    const startId = await maxEventId(db);
    const drained = drainUntil(db, watcher, startId, WRITERS * EVENTS_PER_WRITER, 15000);
    // If an insert below throws, teardown closes the db while drainUntil is
    // still in flight; without a handler its rejection would surface as an
    // unhandled rejection and mask the real failure. The later await still
    // propagates drain errors on the normal path.
    drained.catch(() => {});

    const nextSeq = new Array(WRITERS).fill(1);
    for (const w of schedule) {
      await insertEvent(db, { from: `w${w}`, kind: 'seq', payload: String(nextSeq[w]++) });
    }

    const received = await drained;
    if (received.length !== WRITERS * EVENTS_PER_WRITER) {
      throw new Error(`seed ${seed}: expected ${WRITERS * EVENTS_PER_WRITER} events, got ${received.length}`);
    }
    const ids = new Set(received.map(e => Number(e.id)));
    if (ids.size !== received.length) {
      throw new Error(`seed ${seed}: duplicate deliveries detected`);
    }
    const lastSeq = new Array(WRITERS).fill(0);
    for (const event of received) {
      const w = Number(String(event.from_session).slice(1));
      const seq = Number(event.payload);
      if (seq !== lastSeq[w] + 1) {
        throw new Error(`seed ${seed}: writer w${w} out of order: saw ${seq} after ${lastSeq[w]}`);
      }
      lastSeq[w] = seq;
    }
  } finally {
    watcher.close();
    await db.close();
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

async function main() {
  const driver = loadSqliteDriver();
  if (!driver) {
    console.log('[SKIP] sqlite driver unavailable.');
    process.exit(0);
  }
  console.log(`\n--- property test: per-sender ordering over ${ROUNDS} interleaved schedules ---`);
  for (let i = 0; i < ROUNDS; i++) {
    const seed = (BASE_SEED + i * 2654435761) >>> 0;
    await round(driver, seed);
  }
  console.log(`  PASS all ${ROUNDS} rounds (writers=${WRITERS}, events/writer=${EVENTS_PER_WRITER})`);
  console.log('\n1 passed, 0 failed\n');
}

main().catch(err => {
  console.log(`  FAIL ${err.message}`);
  console.log('\n0 passed, 1 failed\n');
  process.exit(1);
});
